name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: "3.13"
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run linting with ruff
      run: |
        ruff check .
      continue-on-error: true
    
    - name: Run type checking with mypy
      run: |
        mypy jentic_agents --ignore-missing-imports
      continue-on-error: true  # Don't fail the build on mypy errors for now
    
    - name: Run tests with pytest
      run: |
        pytest jentic_agents/tests/ -v --tb=short
      env:
        # Use in-memory ChromaDB for tests to avoid persistence issues
        CHROMA_DB_PATH: ""
    
    - name: Run tests with coverage
      run: |
        pytest jentic_agents/tests/ --cov=jentic_agents --cov-report=xml --cov-report=term-missing
      env:
        CHROMA_DB_PATH: ""
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false 